import 'dart:typed_data';

import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../models/fee_models.dart';

class FeePdfGenerator {
  FeePdfGenerator._();

  static final NumberFormat _moneyFormat = NumberFormat('#,##0.00');

  static String _money(double value) {
    return 'Rs ${_moneyFormat.format(value)}';
  }

  static Future<Uint8List> buildReport({
    required String paymentMonth,
    required List<FeeSummaryRow> rows,
  }) async {
    final pdf = pw.Document(
      title: 'FG Academy Portal - Fee Report $paymentMonth',
      author: 'FG Academy Portal',
      creator: 'FG Academy Portal',
    );

    final collectionRows =
        rows.where((row) => row.section == 'collection').toList()
          ..sort((a, b) => a.sortOrder.compareTo(b.sortOrder));

    final sscTeacherRows =
        rows
            .where((row) => row.section == 'teacher' && row.groupName == 'SSC')
            .toList()
          ..sort((a, b) => a.sortOrder.compareTo(b.sortOrder));

    final hsscTeacherRows =
        rows
            .where((row) => row.section == 'teacher' && row.groupName == 'HSSC')
            .toList()
          ..sort((a, b) => a.sortOrder.compareTo(b.sortOrder));

    final fundRows = rows.where((row) => row.section == 'fund').toList()
      ..sort((a, b) => a.sortOrder.compareTo(b.sortOrder));

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        header: (context) {
          return pw.Container(
            margin: const pw.EdgeInsets.only(bottom: 18),
            padding: const pw.EdgeInsets.all(14),
            decoration: pw.BoxDecoration(
              color: PdfColors.blue900,
              borderRadius: pw.BorderRadius.circular(8),
            ),
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      'FG Academy Portal',
                      style: pw.TextStyle(
                        color: PdfColors.white,
                        fontSize: 18,
                        fontWeight: pw.FontWeight.bold,
                      ),
                    ),
                    pw.SizedBox(height: 3),
                    pw.Text(
                      'Fee Management & Financial Report',
                      style: const pw.TextStyle(
                        color: PdfColors.white,
                        fontSize: 10,
                      ),
                    ),
                  ],
                ),
                pw.Text(
                  paymentMonth,
                  style: pw.TextStyle(
                    color: PdfColors.amber200,
                    fontSize: 14,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
              ],
            ),
          );
        },
        footer: (context) {
          return pw.Container(
            margin: const pw.EdgeInsets.only(top: 16),
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text(
                  'Generated by FG Academy Portal',
                  style: const pw.TextStyle(
                    fontSize: 8,
                    color: PdfColors.grey700,
                  ),
                ),
                pw.Text(
                  'Page ${context.pageNumber} of ${context.pagesCount}',
                  style: const pw.TextStyle(
                    fontSize: 8,
                    color: PdfColors.grey700,
                  ),
                ),
              ],
            ),
          );
        },
        build: (context) {
          return [
            _sectionTitle('1. Total Collection Summary'),
            _collectionTable(collectionRows),
            pw.SizedBox(height: 22),

            _sectionTitle('2. Teacher Payouts - SSC'),
            _teacherTable(sscTeacherRows),
            pw.SizedBox(height: 22),

            _sectionTitle('Teacher Payouts - HSSC'),
            _teacherTable(hsscTeacherRows),
            pw.SizedBox(height: 22),

            _sectionTitle('3. Fund Payouts'),
            _fundTable(fundRows),
          ];
        },
      ),
    );

    return pdf.save();
  }

  static pw.Widget _sectionTitle(String title) {
    return pw.Container(
      width: double.infinity,
      margin: const pw.EdgeInsets.only(bottom: 8),
      padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 7),
      decoration: pw.BoxDecoration(
        color: PdfColors.grey200,
        borderRadius: pw.BorderRadius.circular(5),
      ),
      child: pw.Text(
        title,
        style: pw.TextStyle(
          fontSize: 12,
          fontWeight: pw.FontWeight.bold,
          color: PdfColors.blue900,
        ),
      ),
    );
  }

  static pw.Widget _collectionTable(List<FeeSummaryRow> rows) {
    final data = rows.map((row) {
      return [
        row.itemName,
        _money(row.amount),
        row.paidStudents.toString(),
        row.unpaidStudents.toString(),
      ];
    }).toList();

    return _table(
      headers: const ['Collection', 'Amount', 'Paid', 'Unpaid'],
      data: data,
      rightAlignedColumns: const {1, 2, 3},
    );
  }

  static pw.Widget _teacherTable(List<FeeSummaryRow> rows) {
    final data = rows.map((row) {
      final label = row.itemName == 'Total Teacher Share'
          ? row.itemName
          : feeSubjectLabel(row.itemName);

      return [label, _money(row.amount), row.paidStudents.toString()];
    }).toList();

    return _table(
      headers: const ['Teacher / Subject', 'Payout', 'Students'],
      data: data,
      rightAlignedColumns: const {1, 2},
    );
  }

  static pw.Widget _fundTable(List<FeeSummaryRow> rows) {
    final data = rows.map((row) {
      return [row.itemName, _money(row.amount)];
    }).toList();

    return _table(
      headers: const ['Fund', 'Payout'],
      data: data,
      rightAlignedColumns: const {1},
    );
  }

  static pw.Widget _table({
    required List<String> headers,
    required List<List<String>> data,
    Set<int> rightAlignedColumns = const {},
  }) {
    pw.Widget buildCell(String value, int index, {bool header = false}) {
      return pw.Padding(
        padding: const pw.EdgeInsets.symmetric(horizontal: 7, vertical: 6),
        child: pw.Text(
          value,
          textAlign: rightAlignedColumns.contains(index)
              ? pw.TextAlign.right
              : pw.TextAlign.left,
          style: pw.TextStyle(
            fontSize: header ? 9 : 8.5,
            color: header ? PdfColors.white : PdfColors.grey900,
            fontWeight: header ? pw.FontWeight.bold : pw.FontWeight.normal,
          ),
        ),
      );
    }

    return pw.Table(
      border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
      children: [
        pw.TableRow(
          decoration: const pw.BoxDecoration(color: PdfColors.blueGrey800),
          children: [
            for (int i = 0; i < headers.length; i++)
              buildCell(headers[i], i, header: true),
          ],
        ),
        ...data.map(
          (row) => pw.TableRow(
            children: [
              for (int i = 0; i < row.length; i++) buildCell(row[i], i),
            ],
          ),
        ),
      ],
    );
  }
}
